services:
  - type: web
    name: portfolio-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
